name: Execute Ansible Playbook with Inventory

on:
  workflow_dispatch:
    inputs:
      ansible_playbook_path:
        description: "Path to the Ansible playbook (relative to the repo root)"
        required: true
        default: "conf-containers/playbook.yml"

permissions:
  contents: write

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Create Inventory File
        run: |
          echo "[ec2]" > conf-containers/inventory
          echo "${{ secrets.EC2_PUBLIC_IP }}" >> conf-containers/inventory
          echo "[ec2:vars]" >> conf-containers/inventory
          echo "ansible_user=ec2-user" >> conf-containers/inventory
          echo "ansible_password=${{ secrets.EC2_PASSWORD }}" >> conf-containers/inventory
          echo "ansible_connection=ssh" >> conf-containers/inventory
          echo "ansible_ssh_extra_args='-o StrictHostKeyChecking=no'" >> conf-containers/inventory

      - name: Commit Inventory File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add conf-containers/inventory
          git commit -m "Add dynamic inventory for Ansible"
          git push

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i conf-containers/inventory ${{ github.event.inputs.ansible_playbook_path }}

