name: Deploy with Ansible

on:
  # Manual trigger allows you to provide IP and password on demand
  workflow_dispatch:
    inputs:
      host_ip:
        description: 'IP address of the remote host'
        required: true
        default: '192.168.1.100'
      host_password:
        description: 'Password for the remote host'
        required: true
        default: 'yourpassword'

jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "${{ github.event.inputs.host_ip }}," \
                           --user=your_remote_user \
                           --extra-vars "ansible_ssh_pass=${{ github.event.inputs.host_password }}" \
                           --extra-vars "github_owner=${{ github.repository_owner }}" \
                           playbook.yml

