name: Destroy INSTANCE AWS

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type YES to confirm resource destruction"
        required: true
        default: "NO"

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Confirmation
        if: ${{ github.event.inputs.confirm != 'YES' }}
        run: |
          echo "Destruction not confirmed. Exiting..."
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"

      - name: Initialize Terraform
        run: |
          cd vm-aws
          terraform init

      - name: Destroy Resources
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd vm-aws
          terraform destroy -auto-approve

