name: Launch ec2 isntance in aws 

on:
  workflow_dispatch:
    inputs:
      altair_aws_region:
        description: "aws region"
        required: true
        default: "us-east-1"
      altair_ami_id:
        description: "ami  for ec2"
        required: true
        default: "ami-0c02fb55956c7d316"
      altair_instance_type:
        description: "ec2 type"
        required: true
        default: "t2.micro"
      altair_instance_name:
        description: "Name of the ec2"
        required: true
        default: "AltairInstance"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Version terraform 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"

      - name: Init terraform 
        run: |
          cd vm-aws
          terraform init

      - name: Conf terrafgorm ec2 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd vm-aws
          terraform apply -auto-approve \
            -var="altair_aws_region=${{ github.event.inputs.altair_aws_region }}" \
            -var="altair_ami_id=${{ github.event.inputs.altair_ami_id }}" \
            -var="altair_instance_type=${{ github.event.inputs.altair_instance_type }}" \
            -var="altair_instance_name=${{ github.event.inputs.altair_instance_name }}"

      - name: Salidas
        run: |
          cd vm-aws
          terraform output -json > terraform_outputs.json

      - name: Ip public
        run: |
          PUBLIC_IP=$(jq -r '.altair_instance_public_ip.value' vm-aws/terraform_outputs.json)
          echo "Public IP Address: $PUBLIC_IP"

      - name: Save key 
        run: |
          PRIVATE_KEY=$(jq -r '.altair_private_key.value' vm-aws/terraform_outputs.json)
          echo "$PRIVATE_KEY" > altair_private_key.pem
          chmod 600 altair_private_key.pem
          echo "Private key saved to altair_private_key.pem"

